/* The preparation plan as a runnable scikit-learn script — the pipeline itself,
   not a transformed CSV. A CSV of prepared features is already fitted to one
   split; the script lets the user split, fit on train and apply to test in their
   own environment, and see every decision it makes.

   Mechanical, like cleaningRulesToPandas(): every line comes from the plan, and
   the plan comes from the report. The JS mirror (encode.js) does the same steps,
   so what item 36 measures in the browser is what this script would train on. */

import { MISSING_TOKENS } from "../../components/utils/core/helpers.js";
import { cleaningRulesToPandas } from "../ai/cleaning.js";
import { MAX_CATEGORIES } from "./encode.js";

const py = (s) => JSON.stringify(s);   // a JSON string literal is a valid Python str literal
const pyList = (items) => `[${items.map(py).join(", ")}]`;
const IMPUTE_ORDER = ["mean", "median", "most_frequent"];

/* `options.timeSplit` — { column, cutoff (YYYY-MM-DD), dayFirst } when the report's time
   checks recommend training on earlier rows. The script then carries a SPLIT switch,
   because only the user knows whether the date is when the row was recorded or a fact
   about the entity. `options.model` (default true) adds a first model, cross-validated. */
export function prepPlanToSklearn(plan, cleaningRules = [], options = {}) {
  const { timeSplit = null, model = true } = options;
  const classification = plan.task === "classification";
  const numericBy = Object.fromEntries(IMPUTE_ORDER.map(s => [s, plan.numeric.filter(f => f.impute === s).map(f => f.col)]));
  const numericCols = plan.numeric.map(f => f.col);
  const categoricalCols = plan.categorical.map(f => f.col);
  const indicatorCols = [...plan.numeric, ...plan.categorical].filter(f => f.flag).map(f => f.col).concat(plan.presence);
  const features = [...numericCols, ...categoricalCols, ...plan.presence];

  const lines = [
    `# Preparation pipeline for "${plan.target}" (${plan.task}), generated by Vecto from its report.`,
    "# Every step below is a decision the report states; nothing here is tuned.",
    "# Needs pandas and scikit-learn 1.2 or newer. Replace your_file.csv with your file.",
    "import math",
    "",
    "import pandas as pd",
    "from sklearn.compose import ColumnTransformer",
    "from sklearn.impute import MissingIndicator, SimpleImputer",
    `from sklearn.model_selection import ${[plan.groupBy ? "GroupShuffleSplit" : "train_test_split",
      ...(model ? ["cross_val_score", plan.groupBy ? "GroupKFold" : classification && plan.stratify ? "StratifiedKFold" : "KFold"] : []),
      ...(model && timeSplit ? ["TimeSeriesSplit"] : [])].join(", ")}`,
    ...(model ? [
      classification
        ? "from sklearn.dummy import DummyClassifier\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import balanced_accuracy_score, f1_score"
        : "from sklearn.dummy import DummyRegressor\nfrom sklearn.linear_model import Ridge\nfrom sklearn.metrics import mean_absolute_error, r2_score",
    ] : []),
    "from sklearn.pipeline import make_pipeline",
    "from sklearn.preprocessing import OneHotEncoder, StandardScaler",
    "",
  ];

  if (cleaningRules.length > 0) {
    lines.push("# ── 1. Read, then apply the cleaning rules you accepted ──", cleaningRulesToPandas(cleaningRules));
  } else {
    lines.push(
      "# ── 1. Read every column as text, as the report did ──",
      'df = pd.read_csv("your_file.csv", dtype=str, keep_default_na=False)',
      "",
    );
  }

  lines.push(
    "# ── 2. The values the report counts as missing ──",
    `MISSING = ${pyList([...MISSING_TOKENS])}`,
    "df = df.apply(lambda s: s.mask(s.str.strip().str.lower().isin(MISSING)))",
    "",
    "# ── 3. Columns, as the report decided them ──",
    `TARGET = ${py(plan.target)}`,
    ...IMPUTE_ORDER.filter(s => numericBy[s].length).map(s => `NUMERIC_${s.toUpperCase()} = ${pyList(numericBy[s])}   # missing values filled with the ${s.replace("_", " ")}`),
    `CATEGORICAL = ${pyList(categoricalCols)}`,
    `INDICATORS = ${pyList(indicatorCols)}   # 1 where the value is missing: past 20% missing, or only its presence is kept`,
    `FEATURES = ${pyList(features)}`,
  );
  if (plan.excluded.length > 0) {
    lines.push("# Left out:");
    for (const { col, reason } of plan.excluded) lines.push(`#   ${col} — ${reason}`);
  }

  lines.push(
    "",
    "# ── 4. Rows: the target is never imputed",
    "df = df[df[TARGET].notna()]",
    ...(plan.dropDuplicates ? ["df = df.drop_duplicates()   # a duplicate could sit in train and test at once"] : []),
    "",
    "def level(v):",
    '    """The report\'s grouping key: numbers by value ("1" and "1.0" are one level), text trimmed and lowercased."""',
    "    if pd.isna(v):",
    "        return v",
    "    s = str(v).strip()",
    "    try:",
    "        f = float(s)",
    "        if math.isfinite(f):",
    "            return str(int(f)) if f.is_integer() else repr(f)",
    "    except ValueError:",
    "        pass",
    "    return s.lower()",
    "",
    "for col in NUMERIC_MEAN + NUMERIC_MEDIAN + NUMERIC_MOST_FREQUENT:",
    '    df[col] = pd.to_numeric(df[col].str.strip(), errors="coerce")   # a value that is not a number becomes missing, as in the report',
    "for col in CATEGORICAL:",
    "    df[col] = df[col].map(level)",
    "",
    "X = df[FEATURES]",
    plan.task === "classification"
      ? "y = df[TARGET].map(level)"
      : 'y = pd.to_numeric(df[TARGET].str.strip(), errors="coerce")',
    ...(plan.task === "regression"
      ? ["X, y = X[y.notna()], y[y.notna()]   # a target value that is not a number cannot be predicted as one"]
      : []),
    "",
    "# ── 5. Split FIRST, so nothing below learns from the test rows ──",
  );

  /* The random or grouped split, as lines — indented under the SPLIT switch when a
     time split is offered. */
  const defaultSplit = plan.groupBy
    ? [
        `# Grouped by "${plan.groupBy}": every row of one value stays on one side. test_size counts groups, not rows.`,
        `groups = df.loc[X.index, ${py(plan.groupBy)}].fillna(pd.Series("row " + X.index.astype(str), index=X.index))`,
        "train_idx, test_idx = next(GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42).split(X, y, groups))",
        "X_train, X_test, y_train, y_test = X.iloc[train_idx], X.iloc[test_idx], y.iloc[train_idx], y.iloc[test_idx]",
        "groups_train = groups.iloc[train_idx]",
      ]
    : [
        `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42${plan.stratify ? ", stratify=y" : ""})`,
        ...(classification && !plan.stratify ? ["# Not stratified: a class has a single row, which cannot sit on both sides."] : []),
      ];

  if (timeSplit) {
    lines.push(
      `# The report found that rows move with "${timeSplit.column}" (the Time section). If that column is`,
      "# WHEN each row was recorded, test on the later rows: a random split would test the model",
      "# on the period it learned from. If it describes the entity (a hire or birth date), it is a",
      `# feature, not the time of the row — set SPLIT = ${py(plan.groupBy ? "group" : "random")}.`,
      'SPLIT = "time"',
      "",
      'if SPLIT == "time":',
      `    when = pd.to_datetime(df.loc[X.index, ${py(timeSplit.column)}], errors="coerce", dayfirst=${timeSplit.dayFirst ? "True" : "False"}, utc=True)`,
      `    cutoff = pd.Timestamp(${py(timeSplit.cutoff)}, tz="UTC")   # the first 80% of the period trains`,
      "    order = when[when.notna()].sort_values().index   # rows with no date sit on neither side",
      "    train_rows = [i for i in order if when[i] < cutoff]",
      "    test_rows = [i for i in order if when[i] >= cutoff]",
      "    X_train, X_test, y_train, y_test = X.loc[train_rows], X.loc[test_rows], y.loc[train_rows], y.loc[test_rows]",
      "else:",
      ...defaultSplit.map(l => `    ${l}`),
    );
  } else {
    lines.push(...defaultSplit);
  }

  lines.push(
    "",
    "# ── 6. Preparation, fitted on the training rows only ──",
    "def numeric(strategy):",
    "    return make_pipeline(SimpleImputer(strategy=strategy), StandardScaler())",
    "",
    "preprocess = ColumnTransformer([",
    '    ("numeric_mean", numeric("mean"), NUMERIC_MEAN),',
    '    ("numeric_median", numeric("median"), NUMERIC_MEDIAN),',
    '    ("numeric_most_frequent", numeric("most_frequent"), NUMERIC_MOST_FREQUENT),',
    '    ("categorical", make_pipeline(SimpleImputer(strategy="most_frequent"),',
    `                                  OneHotEncoder(handle_unknown="infrequent_if_exist", max_categories=${MAX_CATEGORIES})), CATEGORICAL),`,
    '    ("indicators", MissingIndicator(features="all"), INDICATORS),',
    "])",
    "",
    "preprocess.fit(X_train)   # medians, means, scales and category lists come from X_train alone",
    "X_train_ready = preprocess.transform(X_train)",
    "X_test_ready = preprocess.transform(X_test)",
    'print("train", X_train_ready.shape, "test", X_test_ready.shape)',
    "",
  );

  if (model) {
    /* The cross-validation splits the training rows the way the train/test split did:
       by group, in time order, stratified, or plainly. The preparation is inside the
       pipeline, so every fold refits it on its own training rows. */
    const cvFor = (kind) => ({
      time:   "TimeSeriesSplit(n_splits=5)   # rows are in date order: each fold tests on later rows",
      group:  "GroupKFold(n_splits=min(5, groups_train.nunique()))   # never more folds than groups",
      strat:  "StratifiedKFold(n_splits=5, shuffle=True, random_state=42)",
      plain:  "KFold(n_splits=5, shuffle=True, random_state=42)",
    })[kind];
    const fallback = plan.groupBy ? "group" : classification && plan.stratify ? "strat" : "plain";
    const cvLines = (kind) => [`cv = ${cvFor(kind)}`, ...(kind === "group" ? ["cv_groups = groups_train"] : ["cv_groups = None"])];
    lines.push(
      "# ── 7. A first model, and what it is worth ──",
      classification
        ? "# Class weights balance the classes, and the score is balanced accuracy — the report's own"
        : "# Ridge regression, scored in R² and mean absolute error against predicting the training mean.",
      ...(classification ? ["# measure — so a model that ignores the smaller classes cannot look good."] : []),
      classification
        ? 'model = make_pipeline(preprocess, LogisticRegression(class_weight="balanced", max_iter=1000))'
        : "model = make_pipeline(preprocess, Ridge(alpha=1.0))",
      classification
        ? 'know_nothing = make_pipeline(preprocess, DummyClassifier(strategy="most_frequent"))'
        : 'know_nothing = make_pipeline(preprocess, DummyRegressor(strategy="mean"))',
      "",
      ...(timeSplit
        ? ['if SPLIT == "time":', ...cvLines("time").map(l => `    ${l}`), "else:", ...cvLines(fallback).map(l => `    ${l}`)]
        : cvLines(fallback)),
      `scores = cross_val_score(model, X_train, y_train, cv=cv, groups=cv_groups, scoring=${py(classification ? "balanced_accuracy" : "r2")})`,
      `print("cross-validated ${classification ? "balanced accuracy" : "R²"} on the training rows: %.3f ± %.3f" % (scores.mean(), scores.std()))`,
      "",
      "model.fit(X_train, y_train)",
      "know_nothing.fit(X_train, y_train)",
      "predicted = model.predict(X_test)",
      ...(classification
        ? [
            'print("test balanced accuracy: %.3f (know-nothing: %.3f)" % (balanced_accuracy_score(y_test, predicted), balanced_accuracy_score(y_test, know_nothing.predict(X_test))))',
            'print("test macro F1: %.3f" % f1_score(y_test, predicted, average="macro"))',
          ]
        : [
            'print("test R²: %.3f (know-nothing: %.3f)" % (r2_score(y_test, predicted), r2_score(y_test, know_nothing.predict(X_test))))',
            'print("test mean absolute error: %.4g" % mean_absolute_error(y_test, predicted))',
          ]),
      "# A floor, not a result: nothing here is tuned. Beat it with better features before a bigger model.",
      "",
    );
  }

  /* Every NUMERIC_* name is read by the loop and the ColumnTransformer above, so
     an empty group is still defined — as an empty list. */
  const defined = IMPUTE_ORDER.filter(s => numericBy[s].length === 0).map(s => `NUMERIC_${s.toUpperCase()} = []`);
  const at = lines.findIndex(l => l.startsWith("CATEGORICAL = "));
  lines.splice(at, 0, ...defined);
  return lines.join("\n");
}

/* The same script as a Jupyter notebook: one code cell per numbered section, each
   under a heading, after a short introduction. Nothing is added or dropped — the
   cells concatenated are the script — so what runs is what was reviewed.
   nbformat 4.4: cells need no ids, and every Jupyter since 2015 opens it. */
export function sklearnToNotebook(code, { title = "Preparation pipeline", intro = [] } = {}) {
  const lines = code.split("\n");
  const cells = [];
  const src = (block) => block.map((l, i) => (i < block.length - 1 ? `${l}\n` : l));
  const markdown = (text) => cells.push({ cell_type: "markdown", metadata: {}, source: src(text.split("\n")) });
  const codeCell = (block) => {
    while (block.length && block[block.length - 1].trim() === "") block.pop();
    if (block.length) cells.push({ cell_type: "code", execution_count: null, metadata: {}, outputs: [], source: src(block) });
  };

  markdown([`# ${title}`, "", ...intro].join("\n"));
  let block = [];
  for (const line of lines) {
    const section = /^# ── (.+?) ──\s*$/.exec(line) ?? /^# ── (.+)$/.exec(line);
    if (section) {
      codeCell(block);
      block = [];
      markdown(`## ${section[1].replace(/\s*──\s*$/, "")}`);
      continue;
    }
    block.push(line);
  }
  codeCell(block);

  return JSON.stringify({
    cells,
    metadata: {
      kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
      language_info: { name: "python" },
    },
    nbformat: 4,
    nbformat_minor: 4,
  }, null, 1);
}
