/* The preparation plan as a runnable scikit-learn script — the pipeline itself,
   not a transformed CSV. A CSV of prepared features is already fitted to one
   split; the script lets the user split, fit on train and apply to test in their
   own environment, and see every decision it makes.

   Mechanical, like cleaningRulesToPandas(): every line comes from the plan, and
   the plan comes from the report. The JS mirror (encode.js) does the same steps,
   so what item 36 measures in the browser is what this script would train on. */

import { MISSING_TOKENS } from "../../components/utils/core/helpers.js";
import { cleaningRulesToPandas } from "../ai/cleaning.js";
import { MAX_CATEGORIES } from "./encode.js";

const py = (s) => JSON.stringify(s);   // a JSON string literal is a valid Python str literal
const pyList = (items) => `[${items.map(py).join(", ")}]`;
const IMPUTE_ORDER = ["mean", "median", "most_frequent"];

export function prepPlanToSklearn(plan, cleaningRules = []) {
  const numericBy = Object.fromEntries(IMPUTE_ORDER.map(s => [s, plan.numeric.filter(f => f.impute === s).map(f => f.col)]));
  const numericCols = plan.numeric.map(f => f.col);
  const categoricalCols = plan.categorical.map(f => f.col);
  const indicatorCols = [...plan.numeric, ...plan.categorical].filter(f => f.flag).map(f => f.col).concat(plan.presence);
  const features = [...numericCols, ...categoricalCols, ...plan.presence];

  const lines = [
    `# Preparation pipeline for "${plan.target}" (${plan.task}), generated by Vecto from its report.`,
    "# Every step below is a decision the report states; nothing here is tuned.",
    "# Needs pandas and scikit-learn 1.2 or newer. Replace your_file.csv with your file.",
    "import math",
    "",
    "import pandas as pd",
    "from sklearn.compose import ColumnTransformer",
    "from sklearn.impute import MissingIndicator, SimpleImputer",
    `from sklearn.model_selection import ${plan.groupBy ? "GroupShuffleSplit" : "train_test_split"}`,
    "from sklearn.pipeline import make_pipeline",
    "from sklearn.preprocessing import OneHotEncoder, StandardScaler",
    "",
  ];

  if (cleaningRules.length > 0) {
    lines.push("# ── 1. Read, then apply the cleaning rules you accepted ──", cleaningRulesToPandas(cleaningRules));
  } else {
    lines.push(
      "# ── 1. Read every column as text, as the report did ──",
      'df = pd.read_csv("your_file.csv", dtype=str, keep_default_na=False)',
      "",
    );
  }

  lines.push(
    "# ── 2. The values the report counts as missing ──",
    `MISSING = ${pyList([...MISSING_TOKENS])}`,
    "df = df.apply(lambda s: s.mask(s.str.strip().str.lower().isin(MISSING)))",
    "",
    "# ── 3. Columns, as the report decided them ──",
    `TARGET = ${py(plan.target)}`,
    ...IMPUTE_ORDER.filter(s => numericBy[s].length).map(s => `NUMERIC_${s.toUpperCase()} = ${pyList(numericBy[s])}   # missing values filled with the ${s.replace("_", " ")}`),
    `CATEGORICAL = ${pyList(categoricalCols)}`,
    `INDICATORS = ${pyList(indicatorCols)}   # 1 where the value is missing: past 20% missing, or only its presence is kept`,
    `FEATURES = ${pyList(features)}`,
  );
  if (plan.excluded.length > 0) {
    lines.push("# Left out:");
    for (const { col, reason } of plan.excluded) lines.push(`#   ${col} — ${reason}`);
  }

  lines.push(
    "",
    "# ── 4. Rows: the target is never imputed",
    "df = df[df[TARGET].notna()]",
    ...(plan.dropDuplicates ? ["df = df.drop_duplicates()   # a duplicate could sit in train and test at once"] : []),
    "",
    "def level(v):",
    '    """The report\'s grouping key: numbers by value ("1" and "1.0" are one level), text trimmed and lowercased."""',
    "    if pd.isna(v):",
    "        return v",
    "    s = str(v).strip()",
    "    try:",
    "        f = float(s)",
    "        if math.isfinite(f):",
    "            return str(int(f)) if f.is_integer() else repr(f)",
    "    except ValueError:",
    "        pass",
    "    return s.lower()",
    "",
    "for col in NUMERIC_MEAN + NUMERIC_MEDIAN + NUMERIC_MOST_FREQUENT:",
    '    df[col] = pd.to_numeric(df[col].str.strip(), errors="coerce")   # a value that is not a number becomes missing, as in the report',
    "for col in CATEGORICAL:",
    "    df[col] = df[col].map(level)",
    "",
    "X = df[FEATURES]",
    plan.task === "classification"
      ? "y = df[TARGET].map(level)"
      : 'y = pd.to_numeric(df[TARGET].str.strip(), errors="coerce")',
    "",
    "# ── 5. Split FIRST, so nothing below learns from the test rows ──",
  );

  if (plan.groupBy) {
    lines.push(
      `# Grouped by "${plan.groupBy}": every row of one value stays on one side. test_size counts groups, not rows.`,
      `groups = df[${py(plan.groupBy)}].fillna(pd.Series("row " + df.index.astype(str), index=df.index))`,
      "train_idx, test_idx = next(GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42).split(X, y, groups))",
      "X_train, X_test, y_train, y_test = X.iloc[train_idx], X.iloc[test_idx], y.iloc[train_idx], y.iloc[test_idx]",
    );
  } else {
    lines.push(
      `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42${plan.stratify ? ", stratify=y" : ""})`,
      ...(plan.task === "classification" && !plan.stratify ? ["# Not stratified: a class has a single row, which cannot sit on both sides."] : []),
    );
  }

  lines.push(
    "",
    "# ── 6. Preparation, fitted on the training rows only ──",
    "def numeric(strategy):",
    "    return make_pipeline(SimpleImputer(strategy=strategy), StandardScaler())",
    "",
    "preprocess = ColumnTransformer([",
    '    ("numeric_mean", numeric("mean"), NUMERIC_MEAN),',
    '    ("numeric_median", numeric("median"), NUMERIC_MEDIAN),',
    '    ("numeric_most_frequent", numeric("most_frequent"), NUMERIC_MOST_FREQUENT),',
    '    ("categorical", make_pipeline(SimpleImputer(strategy="most_frequent"),',
    `                                  OneHotEncoder(handle_unknown="infrequent_if_exist", max_categories=${MAX_CATEGORIES})), CATEGORICAL),`,
    '    ("indicators", MissingIndicator(features="all"), INDICATORS),',
    "])",
    "",
    "preprocess.fit(X_train)   # medians, means, scales and category lists come from X_train alone",
    "X_train_ready = preprocess.transform(X_train)",
    "X_test_ready = preprocess.transform(X_test)",
    'print("train", X_train_ready.shape, "test", X_test_ready.shape)',
    "",
  );

  /* Every NUMERIC_* name is read by the loop and the ColumnTransformer above, so
     an empty group is still defined — as an empty list. */
  const defined = IMPUTE_ORDER.filter(s => numericBy[s].length === 0).map(s => `NUMERIC_${s.toUpperCase()} = []`);
  const at = lines.findIndex(l => l.startsWith("CATEGORICAL = "));
  lines.splice(at, 0, ...defined);
  return lines.join("\n");
}
