/* The script export's second half (lib/prep/sklearn.js): the time-split switch, the
   first model and its cross-validation, and the notebook. The scripts were also run in
   Python (pandas 3, scikit-learn 1.9) on classification, regression, grouped, time and
   grouped-plus-time plans; this file pins the text those runs depended on. */

import { prepPlanToSklearn, sklearnToNotebook } from "../src/lib/prep/sklearn.js";
import { buildPrepPlan } from "../src/lib/prep/plan.js";
import { analyzeWithDiagnostic } from "../src/lib/prep/diagnostic.js";
import { generateSampleData } from "../src/components/utils/core/index.js";

let failed = 0;
const check = (label, ok) => {
  console.log(`${ok ? "PASS" : "FAIL"} ${label}`);
  if (!ok) failed++;
};

const { data, columns } = generateSampleData();
const cls = buildPrepPlan(analyzeWithDiagnostic(data, columns, "churn"));
const reg = buildPrepPlan(analyzeWithDiagnostic(data, columns, "salary"));

const plain = prepPlanToSklearn(cls);
check("a classification script ends with a class-weighted model and a know-nothing one",
  plain.includes('LogisticRegression(class_weight="balanced", max_iter=1000)') && plain.includes('DummyClassifier(strategy="most_frequent")'));
check("it is cross-validated like the split: stratified, in balanced accuracy",
  plain.includes("StratifiedKFold(n_splits=5") && plain.includes('scoring="balanced_accuracy"'));
check("the preparation sits inside the model pipeline, so every fold refits it", plain.includes("make_pipeline(preprocess, LogisticRegression"));
check("without a time split there is no switch", !plain.includes("SPLIT ="));
check("the model is fitted after the split and scored on the test rows only",
  plain.indexOf("train_test_split(") < plain.indexOf("model.fit(X_train, y_train)") && plain.includes("model.predict(X_test)"));

const r = prepPlanToSklearn(reg);
check("a regression script uses Ridge, R² and MAE against the training mean",
  r.includes("Ridge(alpha=1.0)") && r.includes('DummyRegressor(strategy="mean")') && r.includes("mean_absolute_error") && r.includes('scoring="r2"'));

const grouped = prepPlanToSklearn({ ...cls, groupBy: "department", stratify: false });
check("a grouped plan cross-validates by group, never with more folds than groups",
  grouped.includes("GroupKFold(n_splits=min(5, groups_train.nunique()))") && grouped.includes("cv_groups = groups_train"));

const timed = prepPlanToSklearn(cls, [], { timeSplit: { column: "hire_date", cutoff: "2021-03-18", dayFirst: false } });
check("a time split comes behind a SPLIT switch, time by default", timed.includes('SPLIT = "time"') && timed.includes('if SPLIT == "time":'));
check("it names both readings of the date, and how to switch",
  timed.includes("WHEN each row was recorded") && timed.includes('set SPLIT = "random"'));
check("it splits at the report's cutoff, reading dates the report's way",
  timed.includes('pd.Timestamp("2021-03-18", tz="UTC")') && timed.includes("dayfirst=False"));
check("the random split is kept under else, indented", /\nelse:\n {4}X_train, X_test, y_train, y_test = train_test_split\(/.test(timed));
check("the time split cross-validates in date order", timed.includes("TimeSeriesSplit(n_splits=5)"));
check("a day-first file reads its dates day-first",
  prepPlanToSklearn(cls, [], { timeSplit: { column: "d", cutoff: "2020-01-01", dayFirst: true } }).includes("dayfirst=True"));
check("the model can be left out", !prepPlanToSklearn(cls, [], { model: false }).includes("# ── 7."));

/* The notebook is the script, cut at its section headings. */
const nb = JSON.parse(sklearnToNotebook(timed, { title: "Pipeline", intro: ["Generated by Vecto."] }));
check("the notebook is nbformat 4 with a Python kernel", nb.nbformat === 4 && nb.metadata.kernelspec.name === "python3");
check("it opens with a heading, then the imports, then one heading and one code cell per section",
  nb.cells[0].source[0] === "# Pipeline\n" && nb.cells[1].source.join("").includes("import pandas as pd")
  && nb.cells.every((c, i) => c.cell_type === (i % 2 === 0 ? "markdown" : "code")));
const joined = nb.cells.filter(c => c.cell_type === "code").map(c => c.source.join("")).join("\n");
const body = (t) => t.split("\n").filter(l => l.trim() && !l.startsWith("# ──"));
check("its code cells, read in order, are exactly the script", JSON.stringify(body(joined)) === JSON.stringify(body(timed)));
check("code cells start unexecuted", nb.cells.filter(c => c.cell_type === "code").every(c => c.execution_count === null && c.outputs.length === 0));

if (failed) { console.error(`${failed} pipeline check(s) failed`); process.exit(1); }
console.log("all pipeline checks passed");
