/* The browser's only door to the AI layer: POST /api/ai (worker/index.js).

   Never throws. Every outcome — success, a Worker error code, a timeout, no
   network, a cancel — comes back as one shape, because an AI failure must never
   be able to break the page it sits on. The engine report does not depend on it. */

import { readCached, writeCached } from "./answerCache.js";

/* Free models are slow: measured on the eval, nemotron-3-ultra took 24–95 s per
   dossier (openpowerlifting 95 s), and a 120 s limit would have failed real files. */
const TIMEOUT_MS = 180_000;

const MESSAGES = {
  ai_disabled:       "The AI assistant is not configured on this deployment (no API key or no model list).",
  rate_limited:      "Every free model is busy, or today's free quota is spent. Nothing else is affected — try again later.",
  upstream_error:    "The AI provider returned an error — often a busy free model. Trying again may work.",
  empty_response:    "The model returned an empty answer.",
  invalid_json:      "The model's answer was not valid JSON, even after one retry.",
  truncated:         "The model's answer was cut off before it finished — the file may have too many columns for one request.",
  invalid_payload:   "The request was rejected as malformed.",
  payload_too_large: "This dataset's profile is too large to send in one request.",
  /* The account gate. `unauthenticated` is not an error the user caused — the
     panels turn it into a sign-in button rather than printing it. */
  unauthenticated:   "Sign in to run the deeper review. The rest of the report needs no account.",
  quota_exhausted:   "You have used today's deeper reviews. More become available tomorrow — everything else in the report still works.",
  monthly_ceiling:   "You have reached this month's limit for deeper reviews. Everything else in the report still works.",
  budget_exhausted:  "Vecto's shared AI budget for today is spent. Nothing else is affected — try again tomorrow.",
  analysis_request_limit: "This analysis has already made the maximum number of AI requests.",
  invalid_analysis_id:    "The request was rejected as malformed.",
  bad_origin:        "The request was rejected as malformed.",
};

/* A used-up allowance, not a failure — panels draw LimitNotice for these. */
export const isLimitCode = (code) =>
  code === "quota_exhausted" || code === "monthly_ceiling" || code === "budget_exhausted";

/* → { result, model, error, code, detail, aborted, cached, usage } — `error` is a
   sentence for the user, `code` the Worker's machine-readable reason (so a panel can
   tell "sign in" from "the model failed"), `detail` the provider's own message.

   `analysisId` is one id per dataset, generated by Analyze.jsx: every request that
   carries an id the user has already paid for is free, so a wide file sent in six
   parts still costs one of their three monthly analyses. */
export async function requestAi(task, payload, signal, analysisId) {
  const timeout = AbortSignal.timeout(TIMEOUT_MS);
  const fail = (error, detail = null, code = null) => ({ result: null, model: null, error, code, detail, aborted: false });

  /* An answer this browser already has, for this exact task and payload. Only a
     success is ever stored, so a cached reply can never be an error replayed. */
  /* Before the fetch on purpose: a cached answer never reaches the Worker, so it
     can never spend an analysis. That is the whole reason this guard sits here. */
  const cached = await readCached(task, payload);
  if (cached) return { ...cached, error: null, code: null, detail: null, aborted: false, cached: true };

  try {
    const res = await fetch("/api/ai", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "same-origin",
      body: JSON.stringify({ task, payload, analysisId }),
      signal: signal ? AbortSignal.any([signal, timeout]) : timeout,
    });
    const body = await res.json().catch(() => null);
    if (res.ok && body && "result" in body) {
      const answer = { result: body.result, model: body.model ?? null };
      await writeCached(task, payload, answer);
      // `usage` rides on the reply so the page's counter moves without a second call.
      return { ...answer, error: null, code: null, detail: null, aborted: false, cached: false, usage: body.usage ?? null };
    }
    if (!body?.error) {
      return fail(`No AI endpoint answered at /api/ai (HTTP ${res.status}). Locally, run the Worker with \`npx wrangler dev\`.`);
    }
    return {
      ...fail(MESSAGES[body.error] ?? `The AI endpoint answered ${res.status} (${body.error}).`, body.message ?? null, body.error),
      usage: body.usage ?? null,
    };
  } catch {
    if (signal?.aborted) return { ...fail(null), aborted: true };
    if (timeout.aborted) return fail(`The model did not answer within ${TIMEOUT_MS / 1000} seconds.`);
    return fail("Could not reach the AI endpoint.");
  }
}
